const CAMERA_PAGE_NUM = 1;
const ANSWER_PAGE_NUM = -1;
const ANALYZING_PAGE_NUM = 0;
const PROBLEM_PAGE_NUM = 0;
const LOGIN_PAGE_NUM = 0;

export const EXCEPT_PAGES = [CAMERA_PAGE_NUM, ANSWER_PAGE_NUM];
